// Sample papers with real generated videos (streamed from Azure Blob Storage)
export const examplePapers = [
  {
    id: "attention",
    title: "Attention Is All You Need",
    authors: ["Vaswani et al."],
    url: "https://arxiv.org/abs/1706.03762",
    arxivId: "1706.03762",
    realJobId: "mars_attention2",
    blobUrl: "https://banimvideostorage.blob.core.windows.net/videos/mars_attention2/final.mp4",
    venue: "NeurIPS 2017",
    year: 2017,
    duration: 444,
    thumbnailTime: 55,
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    authors: ["Devlin et al."],
    url: "https://arxiv.org/abs/1810.04805",
    arxivId: "1810.04805",
    realJobId: "mars_bert1",
    blobUrl: "https://banimvideostorage.blob.core.windows.net/videos/mars_bert1/final.mp4",
    venue: "NAACL 2019",
    year: 2019,
    duration: 382,
    thumbnailTime: 46,
  },
  {
    id: "contextfocus",
    title: "ContextFocus: Activation Steering for Contextual Faithfulness in LLMs",
    authors: ["Anand et al."],
    url: "https://arxiv.org/abs/2601.04131",
    arxivId: "2601.04131",
    realJobId: "mars_contextfocus1",
    blobUrl: "https://banimvideostorage.blob.core.windows.net/videos/mars_contextfocus1/final.mp4",
    venue: "arXiv 2025",
    year: 2025,
    duration: 397,
    thumbnailTime: 37,
  },
];

// Real scene data extracted from rendered videos (with chapter timestamps)
const attentionScenes = [
  { id: 1, type: "title_card", label: "Attention Is All You Need", duration: 12.85, start: 0.0 },
  { id: 2, type: "section_header", label: "Content", duration: 7.96, start: 12.85 },
  { id: 3, type: "quote_highlight", label: "Core Thesis", duration: 11.88, start: 20.81 },
  { id: 4, type: "multi_metric_cards", label: "Author Affiliations", duration: 10.8, start: 32.69 },
  { id: 5, type: "quote_highlight", label: "Key Quote", duration: 10.3, start: 43.49 },
  { id: 6, type: "flashcard_list", label: "Key Insights from the Abstract", duration: 10.98, start: 53.78 },
  { id: 7, type: "multi_metric_cards", label: "Translation Performance", duration: 13.61, start: 64.76 },
  { id: 8, type: "big_number", label: "Key Metric", duration: 9.72, start: 78.37 },
  { id: 9, type: "quote_highlight", label: "Key Quote", duration: 10.55, start: 88.09 },
  { id: 10, type: "section_header", label: "Introduction", duration: 8.75, start: 98.64 },
  { id: 11, type: "quote_highlight", label: "Key Quote", duration: 10.73, start: 107.39 },
  { id: 12, type: "flashcard_list", label: "Challenges with Recurrent Models", duration: 13.43, start: 118.12 },
  { id: 13, type: "quote_highlight", label: "Key Quote", duration: 9.18, start: 131.54 },
  { id: 14, type: "flashcard_list", label: "Limitations of Current Attention", duration: 8.86, start: 140.72 },
  { id: 15, type: "quote_highlight", label: "Key Quote", duration: 10.62, start: 149.58 },
  { id: 16, type: "big_number", label: "Key Metric", duration: 11.63, start: 160.2 },
  { id: 17, type: "section_header", label: "Related Work", duration: 7.34, start: 171.83 },
  { id: 18, type: "quote_highlight", label: "Key Quote", duration: 9.86, start: 179.17 },
  { id: 19, type: "comparison_split", label: "Relating Input and Output Positions", duration: 14.11, start: 189.04 },
  { id: 20, type: "flashcard_list", label: "Applications of Self-Attention", duration: 14.69, start: 203.15 },
  { id: 21, type: "quote_highlight", label: "Key Quote", duration: 10.55, start: 217.84 },
  { id: 22, type: "section_header", label: "Methodology", duration: 8.53, start: 228.38 },
  { id: 23, type: "image_with_caption", label: "The Transformer Architecture", duration: 10.67, start: 236.92 },
  { id: 24, type: "flashcard_list", label: "Encoder and Decoder Highlights", duration: 11.41, start: 247.58 },
  { id: 25, type: "image_with_caption", label: "Attention Mechanisms", duration: 11.3, start: 259.0 },
  { id: 26, type: "quote_highlight", label: "Key Quote", duration: 10.84, start: 270.3 },
  { id: 27, type: "data_table", label: "Self-Attention vs Other Layers", duration: 9.97, start: 281.13 },
  { id: 28, type: "flashcard_list", label: "Attention Applications", duration: 10.51, start: 291.11 },
  { id: 29, type: "big_number", label: "Key Metric", duration: 8.71, start: 301.62 },
  { id: 30, type: "data_table", label: "Transformer Variations", duration: 9.25, start: 310.33 },
  { id: 31, type: "section_header", label: "Experiments", duration: 9.79, start: 319.58 },
  { id: 32, type: "flashcard_list", label: "Training Setup Highlights", duration: 12.35, start: 329.38 },
  { id: 33, type: "data_table", label: "Machine Translation Results", duration: 12.67, start: 341.72 },
  { id: 34, type: "flashcard_list", label: "Regularization Techniques", duration: 8.78, start: 354.39 },
  { id: 35, type: "data_table", label: "Variations on Transformer Architecture", duration: 9.86, start: 363.18 },
  { id: 36, type: "image_with_caption", label: "Parsing Performance", duration: 8.71, start: 373.04 },
  { id: 37, type: "quote_highlight", label: "Key Quote", duration: 10.84, start: 381.75 },
  { id: 38, type: "section_header", label: "Conclusion", duration: 6.37, start: 392.59 },
  { id: 39, type: "quote_highlight", label: "Key Quote", duration: 8.64, start: 398.96 },
  { id: 40, type: "flashcard_list", label: "Key Achievements", duration: 8.14, start: 407.6 },
  { id: 41, type: "flashcard_list", label: "Future Directions", duration: 10.44, start: 415.73 },
  { id: 42, type: "quote_highlight", label: "Key Quote", duration: 6.8, start: 426.17 },
  { id: 43, type: "closing_card", label: "Key Takeaway", duration: 10.12, start: 432.97 },
];

const bertScenes = [
  { id: 1, type: "title_card", label: "BERT: Pre-training of Deep Bidirectional Transformers", duration: 12.35, start: 0.0 },
  { id: 2, type: "section_header", label: "Content", duration: 5.63, start: 12.35 },
  { id: 3, type: "title_card", label: "BERT Overview", duration: 11.59, start: 17.98 },
  { id: 4, type: "section_header", label: "Abstract", duration: 6.2, start: 29.57 },
  { id: 5, type: "quote_highlight", label: "Core Thesis", duration: 9.5, start: 35.77 },
  { id: 6, type: "flashcard_list", label: "Key Features of BERT", duration: 9.14, start: 45.28 },
  { id: 7, type: "multi_metric_cards", label: "BERT's Performance Highlights", duration: 10.55, start: 54.42 },
  { id: 8, type: "quote_highlight", label: "Key Quote", duration: 9.5, start: 64.97 },
  { id: 9, type: "section_header", label: "Introduction", duration: 7.96, start: 74.47 },
  { id: 10, type: "quote_highlight", label: "Key Quote", duration: 11.2, start: 82.43 },
  { id: 11, type: "flashcard_list", label: "Key NLP Tasks Enhanced by Pre-training", duration: 9.22, start: 93.62 },
  { id: 12, type: "comparison_split", label: "Pre-trained Representation Strategies", duration: 11.23, start: 102.84 },
  { id: 13, type: "quote_highlight", label: "Key Quote", duration: 10.55, start: 114.07 },
  { id: 14, type: "flashcard_list", label: "Limitations of Current Techniques", duration: 10.94, start: 124.62 },
  { id: 15, type: "section_header", label: "Related Work", duration: 7.99, start: 135.56 },
  { id: 16, type: "flashcard_list", label: "Unsupervised Feature-based Approaches", duration: 10.8, start: 143.56 },
  { id: 17, type: "flashcard_list", label: "Unsupervised Fine-tuning Approaches", duration: 11.48, start: 154.36 },
  { id: 18, type: "image_with_caption", label: "Overview of BERT Pre-training and Fine-tuning", duration: 10.27, start: 165.84 },
  { id: 19, type: "flashcard_list", label: "Transfer Learning from Supervised Data", duration: 10.48, start: 176.11 },
  { id: 20, type: "section_header", label: "Experiments", duration: 10.15, start: 186.58 },
  { id: 21, type: "flashcard_list", label: "Evaluation Benchmarks", duration: 13.64, start: 196.74 },
  { id: 22, type: "data_table", label: "GLUE Test Results", duration: 10.33, start: 210.38 },
  { id: 23, type: "image_with_caption", label: "Fine-tuning Procedure", duration: 9.22, start: 220.71 },
  { id: 24, type: "data_table", label: "SQuAD v1.1 Results", duration: 11.09, start: 229.93 },
  { id: 25, type: "data_table", label: "SQuAD v2.0 Results", duration: 9.68, start: 241.02 },
  { id: 26, type: "data_table", label: "SWAG Dataset Results", duration: 9.97, start: 250.7 },
  { id: 27, type: "section_header", label: "Results", duration: 10.12, start: 260.67 },
  { id: 28, type: "flashcard_list", label: "Ablation Studies", duration: 12.49, start: 270.79 },
  { id: 29, type: "data_table", label: "Ablation over Pre-training Tasks", duration: 15.26, start: 283.28 },
  { id: 30, type: "flashcard_list", label: "Effect of Model Size", duration: 10.73, start: 298.54 },
  { id: 31, type: "data_table", label: "Impact of Model Size", duration: 11.99, start: 309.27 },
  { id: 32, type: "flashcard_list", label: "Feature-based vs Fine-tuning", duration: 8.39, start: 321.26 },
  { id: 33, type: "data_table", label: "Feature-based vs Fine-tuning", duration: 9.32, start: 329.65 },
  { id: 34, type: "section_header", label: "Conclusion", duration: 5.37, start: 338.97 },
  { id: 35, type: "quote_highlight", label: "Key Quote", duration: 7.49, start: 344.34 },
  { id: 36, type: "flashcard_list", label: "Key Contributions of BERT", duration: 18.68, start: 351.83 },
  { id: 37, type: "closing_card", label: "Key Takeaway", duration: 10.51, start: 370.51 },
];

const contextfocusScenes = [
  { id: 1, type: "title_card", label: "ContextFocus: Activation Steering for Contextual Faithfulness", duration: 12.74, start: 0.0 },
  { id: 2, type: "title_card", label: "ContextFocus Overview", duration: 16.52, start: 12.74 },
  { id: 3, type: "section_header", label: "Abstract", duration: 6.87, start: 29.27 },
  { id: 4, type: "flashcard_list", label: "Abstract Highlights", duration: 14.69, start: 36.13 },
  { id: 5, type: "quote_highlight", label: "Core Thesis", duration: 9.83, start: 50.82 },
  { id: 6, type: "section_header", label: "Introduction", duration: 9.36, start: 60.65 },
  { id: 7, type: "flashcard_list", label: "Key Challenges in RAG", duration: 12.85, start: 70.01 },
  { id: 8, type: "image_with_caption", label: "Context Faithfulness Example", duration: 13.68, start: 82.86 },
  { id: 9, type: "flashcard_list", label: "Benchmarks for Knowledge Conflict", duration: 13.0, start: 96.54 },
  { id: 10, type: "flashcard_list", label: "Approaches to Improve Context Faithfulness", duration: 13.5, start: 109.54 },
  { id: 11, type: "data_table", label: "Model Outputs in Knowledge Conflict", duration: 11.88, start: 123.04 },
  { id: 12, type: "section_header", label: "Methodology", duration: 11.59, start: 134.92 },
  { id: 13, type: "flashcard_list", label: "Key Components of Methodology", duration: 9.83, start: 146.51 },
  { id: 14, type: "quote_highlight", label: "Key Quote", duration: 9.04, start: 156.34 },
  { id: 15, type: "flashcard_list", label: "How Steering Works", duration: 11.41, start: 165.38 },
  { id: 16, type: "image_with_caption", label: "Layer-wise Evaluation", duration: 12.87, start: 176.79 },
  { id: 17, type: "big_number", label: "Key Metric", duration: 10.15, start: 189.65 },
  { id: 18, type: "flashcard_list", label: "Vector Generation Highlights", duration: 11.45, start: 199.81 },
  { id: 19, type: "quote_highlight", label: "Key Quote", duration: 10.37, start: 211.25 },
  { id: 20, type: "flashcard_list", label: "Vector Addition Process", duration: 10.04, start: 221.62 },
  { id: 21, type: "quote_highlight", label: "Key Quote", duration: 9.0, start: 231.66 },
  { id: 22, type: "section_header", label: "Experiments", duration: 9.83, start: 240.66 },
  { id: 23, type: "flashcard_list", label: "Datasets and Models", duration: 23.83, start: 250.49 },
  { id: 24, type: "quote_highlight", label: "Key Quote", duration: 12.31, start: 274.32 },
  { id: 25, type: "data_table", label: "Qualitative Examples", duration: 9.61, start: 286.64 },
  { id: 26, type: "data_table", label: "Performance on ConFiQA Benchmark", duration: 12.1, start: 296.25 },
  { id: 27, type: "data_table", label: "Inference-Time Latency Comparison", duration: 9.86, start: 308.35 },
  { id: 28, type: "data_table", label: "Effects of Steering Vector Components", duration: 11.45, start: 318.21 },
  { id: 29, type: "section_header", label: "Conclusion", duration: 6.6, start: 329.66 },
  { id: 30, type: "flashcard_list", label: "Key Takeaways", duration: 14.15, start: 336.26 },
  { id: 31, type: "quote_highlight", label: "Key Quote", duration: 9.25, start: 350.4 },
  { id: 32, type: "multi_metric_cards", label: "Performance Highlights", duration: 12.67, start: 359.66 },
  { id: 33, type: "flashcard_list", label: "Future Directions", duration: 12.02, start: 372.33 },
  { id: 34, type: "closing_card", label: "Key Takeaway", duration: 11.88, start: 384.35 },
];

// Minimal mock data for demo/fallback mode
export const mockPaperData: Record<string, any> = {
  attention: {
    title: "Attention Is All You Need",
    authors: ["Vaswani et al."],
    venue: "NeurIPS 2017",
    year: 2017,
    url: "https://arxiv.org/abs/1706.03762",
    abstract: "We propose the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.",
    sections: [
      { id: "intro", title: "Introduction", content: "The Transformer replaces recurrent layers with multi-headed self-attention." },
      { id: "results", title: "Results", content: "Achieves 28.4 BLEU on WMT 2014 English-to-German." },
    ],
    scenes: attentionScenes,
    duration: 444,
  },
  bert: {
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    authors: ["Devlin et al."],
    venue: "NAACL 2019",
    year: 2019,
    url: "https://arxiv.org/abs/1810.04805",
    abstract: "BERT pre-trains deep bidirectional representations by jointly conditioning on both left and right context.",
    sections: [
      { id: "intro", title: "Introduction", content: "BERT uses masked language modeling for bidirectional pre-training." },
      { id: "results", title: "Results", content: "State-of-the-art on 11 NLP tasks including GLUE (80.5%) and SQuAD (93.2 F1)." },
    ],
    scenes: bertScenes,
    duration: 382,
  },
  contextfocus: {
    title: "ContextFocus: Activation Steering for Contextual Faithfulness in Large Language Models",
    authors: ["Anand et al."],
    venue: "arXiv",
    year: 2025,
    url: "https://arxiv.org/abs/2601.04131",
    abstract: "A lightweight activation steering method that enhances faithfulness to retrieved context without fine-tuning.",
    sections: [
      { id: "intro", title: "Introduction", content: "LLMs struggle with contextual faithfulness when context conflicts with parametric memory." },
      { id: "results", title: "Results", content: "Outperforms ContextDPO and COIECD on the ConFiQA benchmark." },
    ],
    scenes: contextfocusScenes,
    duration: 397,
  },
};
